version: "3.5"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.10
    # To secure MongoDB, uncomment and set the following values
    volumes:
      - ./db_data:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/